# docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      LLAMA_MODELS_DIR: /app/models
      LLAMA_DATA_DIR: /app/data
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./models:/app/models
      - ./backend/data:/app/data
    command: bash -c "uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload"

  crew_runner:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: "no"
    environment:
      LLAMA_MODELS_DIR: /app/models
      LLAMA_DATA_DIR: /app/data
      PYTHONPATH: /app
    volumes:
      - ./models:/app/models
      - ./backend/data:/app/data
    command: bash -c "python crewai_agents/main.py"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:8000/api